dataset: ./dataset/coco_train_singlelabel.txt
data: /home/wangao/datasets/coco
num_classes: 80
n_ctx: 4
checkpoint: scpnet+coco
ctx_init: a photo of a
log_file: scpnet+coco.txt
epochs: 60
total_epochs: 80
lr: 3e-5
lambda_u: 0.125
p_cutoff: 0.95
hard_k: 2
kl_lambda: 1
T: 0.2
sparse_topk: 62
reweight_p: 0.2
gcn_lr: 1e-5
relation_file: relation+coco.npy
ratio: 1
scale: 10
