data: /home/wangao/datasets/nuswide/
train_dataset: ./dataset/nus_train_singlelabel.txt
val_dataset: ./dataset/nus_val.txt
num_classes: 81
n_ctx: 4
checkpoint: scpnet+nuswide
ctx_init: a photo of a
log_file: scpnet+nuswide.txt
epochs: 60
lr: 3e-5
lambda_u: 0.125
p_cutoff: 0.95
hard_k: 6
kl_lambda: 1
T: 0.2
sparse_topk: 50
reweight_p: 0.2
gcn_lr: 1e-4
relation_file: relation+nuswide.npy
ratio: 1
scale: clip